services:
  mysql:
    image: mysql:8.0.36
    networks:
      - minipay_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul # TimeZone 설정
      - MYSQL_DATABASE=minipay
      - MYSQL_USER=minipay_user
      - MYSQL_PASSWORD=minipay_password
      - MYSQL_ROOT_PASSWORD=root_password

  membership-service:
    image: mini-pay-membership:1.0.0
    networks:
      - minipay_network
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/minipay?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=minipay_user
      - SPRING_DATASOURCE_PASSWORD=minipay_password

networks:
  minipay_network:
    driver: bridge