CREATE DATABASE IF NOT EXISTS membership;
CREATE DATABASE IF NOT EXISTS banking;
CREATE DATABASE IF NOT EXISTS money;

GRANT ALL PRIVILEGES ON membership.* TO 'minipay_user'@'%';
GRANT ALL PRIVILEGES ON banking.* TO 'minipay_user'@'%';
GRANT ALL PRIVILEGES ON money.* TO 'minipay_user'@'%';

FLUSH PRIVILEGES;