server:
  port: 8084

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      connection-timeout: 5000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_CLUSTER_BOOTSTRAP_SERVERS}
    producer:
      acks: all