server:
  port: 8080

minipay:
  token:
    secret: ${JWT_SECRET}
    token-type: Bearer
  membership:
    url: ${MINIPAY_MEMBERSHIP_URL}
  banking:
    url: ${MINIPAY_BANKING_URL}
  money:
    url: ${MINIPAY_MONEY_URL}
  remittance:
    url: ${MINIPAY_REMITTANCE_URL}
  payment:
    url: ${MINIPAY_PAYMENT_URL}
  query:
    url: ${MINIPAY_QUERY_URL}