spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      connection-timeout: 5000
      validation-timeout: 5000
  sql:
    init:
      mode: never
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    open-in-view: false
    defer-datasource-initialization: true

minipay:
  payment:
    url: ${MINIPAY_PAYMENT_URL}
  money:
    url: ${MINIPAY_MONEY_URL}
  banking:
    url: ${MINIPAY_BANKING_URL}